config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes
  root "notes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  
  scope :new_order, -> { order(created_at: :desc) }
  
  paginates_per 3
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  def index
    @note = Note.new
    #昇順だったら :asc
    @notes = Note.new_order.page(params[:page])
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to notes_path, notice: "メモを登録しました"
    else
      render :index
    end
  end
  
  def edit
    @note = Note.find(params[:id])
    @notes = Note.new_order
    render action: :index
  end
  
  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      redirect_to notes_path, notice: "メモを更新しました"
    else
      render :index
    end
  end
  
  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to notes_path, notice: "メモを削除しました"
  end
  
  private
  
  def note_params
    # ストロングパラメータはフォームで入力した内容を受け取る
    params.require(:note).permit(:title, :body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/notes">MyNote</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "設定変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mynote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="container">
      <div class="row">
        <% if notice.present? %>
          <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <p><%= notice %></p>
          </div>
        <% end %>

        <% if alert.present? %>
          <div class="alert alert-dismissable alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <p><%= alert %></p>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: note, local: true do |form| %>
  <% if note.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= note.errors.count %>件のエラーがあります</b></p>

    <ul>
    <% note.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :body %><br>
    <%= form.text_area :body, class: "form-control", rows: 15 %>
  </div>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.submit class: "btn btn-default" %>
<% end %>

app/views/notes/index.html.erb
<div class="col-md-5">
  <% @notes.each do |note| %>
    <div class="right-contents">
      <%= link_to(edit_note_path(note)) do %> 
        <%= fa_icon 'pencil 2x', class: "note-edit" %>
      <% end %>
      <%= link_to(note_path(note), method: :delete) do %> 
        <%= fa_icon 'trash 2x', class: "note-delete" %>
      <% end %>
    </div>
    <h4><%= note.title %></h4>
    <%= simple_format(truncate(note.body)) %>
    <hr>
  <% end %>
  <%= paginate @notes %>
</div>
<div class="col-md-7">
  <%= render partial: 'form', locals: { note: @note } %>
  <%= link_to "New Note", notes_path, class: "btn btn-primary pull-right" %>
</div>